### ISSUE TITLE
Repo/data out of date?

### ISSUE THREAD

**Issue by devinmatte** [thomasforth/parkulator#1]
https://imactivate.com/parkulator/ seems to work for the whole world (or at least from my testing, north America) but the repo here seems to only have data for Great Britain. Is it possible to get the raw data you're using for the rest of the world?
I was hoping to get this data for a transit/housing related project. Any help would be great.
Thanks for this project!

**Comment by devinmatte** [comment]
As I'm reading the README further it would appear we can probably do this ourselves, but still it would be great to see how the current live service works, as it does appear the code has changed since this repo was last updated

**Comment by thomasforth** [comment]
Hello,

Since I wrote this someone else has massively improved the methodology and is able to power their equivalent tool directly using Open Street Map queries. You may have much more luck following their examples at https://open-innovations.github.io/parkulator/ which is more actively maintained on GitHub at https://github.com/open-innovations/parkulator/

**Comment by devinmatte** [comment]
Oh wow, thanks for linking this to me. I'll take a look there instead. Thanks for the original project, it's been useful in advocating for reducing parking mandates!
